#!/bin/sh
set -e

isShell ()
{
	for s in \
		"/bin/bash" \
		"bash" \
		"sh" \
		"/bin/sh"
	do
		if [ -z "${cmd#"$1"}" ]; then
			return 0
		fi
	done

	return 1
}

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]
then
	set -- gitlab "$@"
# first arg is "gitlab"
elif [ "$1" = "gitlab" ]
then
	set -- /bin/bash -- "$@"
# first arg is a shell
elif isShell "$1"
then
	set -- "$@"
fi

exec gitlab "$@"
